[package]
name = "blink"
version = "0.1.0"
authors = ["maurizio.conti@fablabromagna.org"]

[dependencies]
panic-abort = "0.1.1"

[dependencies.stm32f1]
version = "0.1.0"
features = ["stm32f100", "rt"] 